version: "{branch}-{build}"
image: Visual Studio 2017
build: off
cache:
  - '%userprofile%\AppData\Local\pip'
environment:
  matrix:
    - PYTHON: 'C:\\Python27'
      TOXENV: "py27"
    - PYTHON: 'C:\\Python27-x64'
      TOXENV: "py27"
    # - PYTHON: 'C:\\Python34'
    #   TOXENV: "py34"
    # - PYTHON: 'C:\\Python34-x64'
    #   TOXENV: "py34"
    - PYTHON: 'C:\\Python35'
      TOXENV: "py35"
    - PYTHON: 'C:\\Python35-x64'
      TOXENV: "py35"
    - PYTHON: 'C:\\Python36'
      TOXENV: "py36"
    - PYTHON: 'C:\\Python36-x64'
      TOXENV: "py36"
    - PYTHON: 'C:\\Python37'
      TOXENV: "py37"
    - PYTHON: 'C:\\Python37-x64'
      TOXENV: "py37"
    - PYTHON: 'C:\\Python38'
      TOXENV: "py38"
    - PYTHON: 'C:\\Python38-x64'
      TOXENV: "py38"

install:
  - '%PYTHON%\python -V'
  - '%PYTHON%\python -m pip install tox'

test_script:
  - '%PYTHON%\Scripts\tox'

pull_requests:
  do_not_increment_build_number: true

on_failure:
  - ps: dir 'env:'
  - ps: get-content .tox\*\log\*
